### ISSUE TITLE
Can somebody run this project and add screenshots of UI of this project

### ISSUE THREAD

**Issue by SalahudinMalik** [SalahudinMalik/Rent-A-Car-Management-System#1]
Please run this project in Visual Studio, generate DB from the project, and Share the UI of this project in Readme File.

**Comment by codetravellearn** [comment]
YUP I CAN!

**Comment by sheershakx** [comment]
Since i work daily on asp.net c# projects , its an easy and fast job for me .

**Comment by SalahudinMalik** [comment]
> Since i work daily on asp.net c# projects , its an easy and fast job for me .

@sheershakx sure please go ahead
